#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace at.Wordpress.Dataverse.Types
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum At_ContactRole
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alumni", 0)]
		Alumni = 120990000,
	}
}
#pragma warning restore CS1591
